### ISSUE TITLE
Generate Changelog

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#7]
Hi, @DIOHz0r 

In every release you need to generate and push the changelog file to the gh-pages with this header:

```YAML
---
layout: modal
title: changelog
---
```
