### ISSUE TITLE
GitHub App Settings

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#9]
Hi, @Naylin15 

- Create a file `settings.yml` in the folder `.github` (content below in the issue)
- Commit the file with this commit message: `build(settings): add YAML for the bot Settings`
- Create a Pull-Request
- Repeat the steps for each repository, changing the proper name, topics, homepage and description.

```YAML
repository:
  name: composer-package-glpi
  description:  GLPI API Client Library for PHP
  homepage: http://flyve.org/composer-package-glpi/
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
labels:
  - name: bug
    color: f44336
  - name: build
    color: 795548
  - name: ci
    color: fbca04
  - name: documentation
    color: 607d8b
  - name: duplicate
    color: 9e9e9e
  - name: feature
    color: 3f51b5
  - name: hacktoberfest
    color: ff625f
  - name: invalid
    color: cddc39
  - name: performance
    color: 009688
  - name: question
    color: ff5722
  - name: refactor
    color: 9c27b0
  - name: style
    color: 2196f3
  - name: test
    color: 8bc34a
  - name: wontfix
    color: ffffff
  - name: help wanted
    color: 33aa3f
  - name: good first issue
    color: 7057ff
```
